### PR TITLE
Correction of typos.

### PR DESCRIPTION
**Pull request by paulodamaso**
Typo and punctuation corrections / suggestions.

I'd like to report also:
- there is an incomplete line in `arc-deck.tex`, which lacks references to advantages of chatbot architecture
- "disappointed" work in `freelance-deck.tex` looks like out of context; who is disappointed?
- "Brave", in  `freelance-deck.tex` line 190, should be in green color, since it is a quality and not a flaw of freelance developers

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#67](https://github.com/zold-io/papers/issues/67) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#67](https://github.com/zold-io/papers/issues/67); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@paulodamaso thanks a lot!

**Comment by yegor256** [comment]
@paulodamaso typos removed in c72ee76

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.3`

**Comment by paulodamaso** [comment]
@yegor256 Great!

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#67` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#67](https://github.com/zold-io/papers/issues/67) is now out of scope

**Pull request merged**
