### PR TITLE
Update wp.tex

### PR DESCRIPTION
**Pull request by silverbonegg**
Noticed a mistake in my edit:

"The amount of Taxes depends two factors: 1) the number..." should read, "The amount of Taxes depends **on** two factors: 1) the number..."

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#8](https://github.com/zold-io/papers/issues/8) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@silverbonegg thanks!

**Comment by 0crat** [comment]
The job [#8](https://github.com/zold-io/papers/issues/8) is now out of scope

**Pull request merged**
