### PR TITLE
Update wp.tex

### PR DESCRIPTION
**Pull request by jolly-jelly**
Included more currencies in table on transaction fees.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#31](https://github.com/zold-io/papers/issues/31) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#31` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#31](https://github.com/zold-io/papers/issues/31) is now out of scope

**Pull request merged**
